---
- hosts: dev
  user: root
  vars:
          anil:
                  - apache2
                  - sshd
                  - vsftpd  
  tasks:   
          
          - name: remove apache
            package: name=apache2 state=absent
            tags:
              - rmapache
          - name: remove openssh
            package: name=openssh-server state=absent
          
          - name: remove vsftpd
            package: name=vsftpd state=absent

          - name: install apache
            package: name=apache2 state=present
            tags:
                - apache2
            notify:
                    #- restart-apache2
                    #  - variable 
          - name: install ssh
            package:  name=openssh-server state=present
            tags:
                - ssh
            notify: 
            # - ssh-restart2 
                     #- variable     
          - name: install vsftpd
            package: name=vsftpd state=present
            tags:
                - vsftpd
            notify:
                  - restart-vsftpd2  
                  - restart-apache2
                  - ssh-restart2        
                    # - variable    
          - name: install git
            package: name=git state=present

          - name: install jdk
            package: name=default-jdk state=present

          - name: install maven
            package: name=maven state=present
   
  handlers:
          # - name: variable
          #    service: name= "{{anil}}" state=restarted
             - name: restart-apache2
               service: name=apache2 state=restarted
               tags:
                    - checking    
               notify:
                    - ssh-restart2
             - name: ssh-restart2
               service: name=sshd state=restarted
               notify:
                    - restart-apache2  
             - name: restart-vsftpd2
               service: name=vsftpd state=restarted  
           
            # -name: install apche
          #package:
          #        name=apache 
          #         state=installed
           # -name: install vsftpd
           #package:name=vsftpd state=present
           # -name: install ssh
           # package:name=openssh state=present
